from locators.site_map.maps_locators import SiteMap, KazanSiteMap, RyazanSiteMap, PolSiteMap, MolSiteMap
import allure
import time
from pages.base_page import BasePage


class CheckTheMap(BasePage):
    @allure.step("Проверить является ли страница недоступной")
    def click_on_url_and_back_msk_101(self):
        url_click = [SiteMap.INTERNET_MSK,
                     SiteMap.MAP_PROVIDERS,
                     SiteMap.INTERNET_PRIVATE_HOME,
                     SiteMap.PROVIDERS_IN_MSK,
                     SiteMap.INTERNET_IN_OFFICE,
                     SiteMap.TENDER_OFFICE,
                     SiteMap.INTERNET_PROV_MSK,
                     SiteMap.MOBILE_OPERATORS,
                     SiteMap.INTERNET_TARIFFS,
                     SiteMap.REVIEWS_HOME_INTERNET,
                     SiteMap.SALES_HOME_INTERNET,
                     SiteMap.TARIFFS_NETWORK,
                     SiteMap.CHOOSE_NUMBER,
                     SiteMap.RANGE_INTERNET_PROV,
                     SiteMap.CONTACTS,
                     SiteMap.TARIFFS_HOME_INTERNET,
                     SiteMap.HOME_INTERNET,
                     SiteMap.TARIFFS_INTERNET_TV,
                     SiteMap.CHEAP_INTERNET,
                     SiteMap.INTERNET_100,
                     SiteMap.INTERNET_300,
                     SiteMap.INTERNET_500,
                     SiteMap.TARIFFS_CINEMA
                     ]
        for url in url_click:
            try:
                element = self.element_is_visible(url)
                element.click()
                self.driver.back()
                print(f"Проверка {url} на карте покрытия пройдена")
            except AssertionError:
                print(f"Возникла ошибка с {url}")

    @allure.step("Проверить является ли страница недоступной")
    def click_on_url_and_back_kaz_101(self):
        url_click = [
            KazanSiteMap.INTERNET_KAZ,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_SBER,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_BEELINE,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_MTC,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_MEGAFONE,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_YOTA,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_TELE_2,
            KazanSiteMap.OPERATOR_MOBILE_NETWORK_TINKOFF,
            KazanSiteMap.PROVIDERS_KAZAN,
            KazanSiteMap.INTERNET_PRIVATE_HOME,
            KazanSiteMap.PROVIDERS_ADDRESS,
            KazanSiteMap.INTERNET_IN_OFFICE,
            KazanSiteMap.TENDER_IN_OFFICE,
            KazanSiteMap.INTERNET_PROVIDERS,
            KazanSiteMap.MOBILE_OPERATORS,
            KazanSiteMap.INTERNET_TARIFFS,
            KazanSiteMap.REVIEW_HOME_INTERNET,
            KazanSiteMap.HOME_INTERNET_TBT,
            KazanSiteMap.HOME_INTERNET_SYNTERRA,
            KazanSiteMap.HOME_INTERNET_TTK,
            KazanSiteMap.HOME_INTERNET_ENFORTA,
            KazanSiteMap.HOME_INTERNET_BEELINE,
            KazanSiteMap.HOME_INTERNET_DOMRU,
            KazanSiteMap.HOME_INTERNET_TELEBIT,
            KazanSiteMap.HOME_INTERNET_TATTELECOM,
            KazanSiteMap.HOME_INTERNET_ORANGE,
            KazanSiteMap.HOME_INTERNET_NEKSTRIM,
            KazanSiteMap.HOME_INTERNET_CITYCOM,
            KazanSiteMap.HOME_INTERNET_FATUM,
            KazanSiteMap.HOME_INTERNET_AKKORD,
            KazanSiteMap.HOME_INTERNET_SKYNET,
            KazanSiteMap.HOME_INTERNET_TELECOM,
            KazanSiteMap.HOME_INTERNET_TATAIRS,
            KazanSiteMap.HOME_INTERNET_OBIT,
            KazanSiteMap.HOME_INTERNET_GOLDEN_TELEKOM,
            KazanSiteMap.HOME_INTERNET_PROSTOR,
            KazanSiteMap.HOME_INTERNET_MELT,
            KazanSiteMap.HOME_INTERNET_DOMRU_BUSINESS,
            KazanSiteMap.HOME_INTERNET_UFANET,
            KazanSiteMap.HOME_INTERNET_RAINBOW,
            KazanSiteMap.HOME_INTERNET_YOTA,
            KazanSiteMap.HOME_INTERNET_MEGAFONE,
            KazanSiteMap.HOME_INTERNET_SVYAZENERGO,
            KazanSiteMap.HOME_INTERNET_TELESET,
            KazanSiteMap.HOME_INTERNET_UNITEL,
            KazanSiteMap.HOME_INTERNET_21,
            KazanSiteMap.HOME_INTERNET_MTC,
            KazanSiteMap.HOME_INTERNET_TATALECOM,
            KazanSiteMap.HOME_INTERNET_TELE_2,
            KazanSiteMap.HOME_INTERNET_LETAI,
            KazanSiteMap.REV_INTERNET_TVT,
            KazanSiteMap.REV_INTERNET_TTK_KAZ,
            KazanSiteMap.REV_ENFORTA,
            KazanSiteMap.REV_BEELINE,
            KazanSiteMap.REV_DOMRU,
            KazanSiteMap.REV_TATTELECOM,
            KazanSiteMap.REV_NEXTRIM,
            KazanSiteMap.REV_SKYNET,
            KazanSiteMap.REV_TELECOM,
            KazanSiteMap.REV_TELESET,
            KazanSiteMap.REV_ROSTELECOM,
            KazanSiteMap.SALES_HOME_INTERNET,
            KazanSiteMap.CHOOSE_NUMBER,
            KazanSiteMap.MOBILE_TARIFFS_BEELINE,
            KazanSiteMap.MOBILE_TARIFFS_YOTA,
            KazanSiteMap.CHOOSE_NUMBER_SBERMOB,
            KazanSiteMap.CHOOSE_NUBMER_YOTA,
            KazanSiteMap.CONTACTS,
            KazanSiteMap.HOME_INTERNET_KAZ,
            KazanSiteMap.TARIFFS_CINEMA,
            KazanSiteMap.TARIFFS_MGTS,
            KazanSiteMap.TARIFFS_BEELINE,
            KazanSiteMap.COOL_TARIFFS_BEELINE,
            KazanSiteMap.COOL_TARIFFS_DOMRU,
            KazanSiteMap.TARIFFS_TATTELECOM_HOME,
            KazanSiteMap.TARIFFS_UFANET_HOME,
            KazanSiteMap.TARIFFS_MTS_HOME,
            KazanSiteMap.COOL_TARIFFS_MTS,
            KazanSiteMap.TARIFFS_ROSTELECOM_MOB,
            KazanSiteMap.TARIFFS_ROSTELECOM_CINEMA,
            KazanSiteMap.HOME_INTERNET_TELE2,
            KazanSiteMap.TARIFFS_HOME_INTERNET_CINIMA,
            KazanSiteMap.TARIFFS_HOME_INTERNET_LETAY,
            KazanSiteMap.COOL_TARIFFS_HOME_INTERNET_LETAY,
        ]
        for url in url_click:
            try:
                element = self.element_is_visible(url)
                element.click()
                self.driver.back()
                print(f"Проверка {url} на карте покрытия пройдена")
            except AssertionError:
                print(f"Возникла ошибка с {url}")

    @allure.step("Проверить является ли страница недоступной")
    def click_on_url_and_back_ryaz_101(self):
        url_click = [
            RyazanSiteMap.INTERNET_RYAZ,
            RyazanSiteMap.OPERATOR_MOBILE_NETWORK,
            RyazanSiteMap.OPERATOR_MOBILE_YOTA,
            RyazanSiteMap.OPERATOR_MOBILE_MEGAFON,
            RyazanSiteMap.OPERATOR_MOBILE_MTC,
            RyazanSiteMap.OPERATOR_MOBILE_TELE2,
            RyazanSiteMap.OPERATOR_MOBILE_MOBILE,
            RyazanSiteMap.OPERATOR_MOBILE_BEELINE,
            RyazanSiteMap.MAP_PROVIDERS_RYAZ,
            RyazanSiteMap.INTERNET_PRIVATE_HOME,
            RyazanSiteMap.PROVIDERS_INTERNET,
            RyazanSiteMap.INTERNET_IN_OFFICE,
            RyazanSiteMap.TENDER_IN_INTERNET,
            RyazanSiteMap.INTERNET_PROVIDER_RYAZ,
            RyazanSiteMap.MOBILE_NETWORK,
            RyazanSiteMap.INTERNET_TARIFFS,
            RyazanSiteMap.REVIEW_HOME_INTERNET,
            RyazanSiteMap.HOME_INTERNET_SPARK,
            RyazanSiteMap.HOME_INTERNET_ENFORTA,
            RyazanSiteMap.HOME_INTERNET_PROSTOR,
            RyazanSiteMap.HOME_INTERNET_ALOUN,
            RyazanSiteMap.HOME_INTERNET_INET,
            RyazanSiteMap.HOME_INTERNET_SOTCOM,
            RyazanSiteMap.HOME_INTERNET_MTC,
            RyazanSiteMap.HOME_INTERNET_SKYLINK,
            RyazanSiteMap.HOME_INTERNET_SINTERA,
            RyazanSiteMap.HOME_INTERNET_DOMRU,
            RyazanSiteMap.PROVIDER_POSTELECOM,
            RyazanSiteMap.HOME_INTERNET_RADUGA,
            RyazanSiteMap.HOME_INTERNET_SILON,
            RyazanSiteMap.HOME_INTERNET_YOTA,
            RyazanSiteMap.HOME_INTERNET_WIFI,
            RyazanSiteMap.HOME_INTERNET_MEGAFONE,
            RyazanSiteMap.ACTIONS_H0ME_INTERNET,
            RyazanSiteMap.REVIEWS_PROVIDER_PROSTOR,
            RyazanSiteMap.REVIEWS_PROVIDER_ANLINK,
            RyazanSiteMap.REVIEWS_PROVIDER_MTC,
            RyazanSiteMap.REVIEWS_PROVIDER_SKYLINK,
            RyazanSiteMap.REVIEWS_PROVIDER_DOMRU,
            RyazanSiteMap.REVIEWS_PROVIDER_RUAZ,
            RyazanSiteMap.REVIEWS_PROVIDER_MEGAFON,
            RyazanSiteMap.CHOOSE_NUMBER,
            RyazanSiteMap.TARIFFS_NETWORK,
            RyazanSiteMap.TARIFFS_YOTA,
            RyazanSiteMap.TARIFFS_TELE2,
            RyazanSiteMap.TARIFFS_BEELINE,
            RyazanSiteMap.CHOOSE_NUMBER_SBER,
            RyazanSiteMap.CHOOSE_NUMBER_MTC,
            RyazanSiteMap.CHOOSE_NUMBER_TINKOFF,
            RyazanSiteMap.CONTACTS,
            RyazanSiteMap.TARIFFS_INTERNET_MOBILE,
            RyazanSiteMap.HOME_INTERNET_RYAZ,
            RyazanSiteMap.CHEAP_HOME_INTERNET,
            RyazanSiteMap.CHEAP_HOME_INTERNET_300,
            RyazanSiteMap.TARIFFS_CINEMA,
            RyazanSiteMap.TARIFFS_MGTC,
            RyazanSiteMap.TARIFFS_MTC_HOME,
            RyazanSiteMap.HOME_INTERNET_MTC_R,
            RyazanSiteMap.TARIFFS_DOMRU,
            RyazanSiteMap.TARIFFS_DOMRU_CINEMA,
            RyazanSiteMap.TARIFFS_ROSTELECOM,
            RyazanSiteMap.TARIFFS_ROSTELECOM_CINEMA,
            RyazanSiteMap.TARIFFS_TTK,
            RyazanSiteMap.TARIFFS_MEGAFON,
            RyazanSiteMap.TARIFFS_MEGAFON_COOL,
            RyazanSiteMap.TARIFFS_TELE2_COOL,
            RyazanSiteMap.TARIFFS_TELE2_COOL_INTER,
            RyazanSiteMap.TARIFFS_TELE2_COOL_CINEMA
        ]
        for url in url_click:
            try:
                element = self.element_is_visible(url)
                element.click()
                self.driver.back()
                print(f"Проверка {url} на карте покрытия пройдена")
            except AssertionError:
                print(f"Возникла ошибка с {url}")

    @allure.step("Проверить является ли страница недоступной")
    def click_on_url_and_back_pol_spb(self):
        url_click = [
            PolSiteMap.HOME_INTERNET,
            PolSiteMap.HOME_INTERNET_TARIFFS_TIERA,
            PolSiteMap.HOME_INTERNET_TARIFFS_DOMRU,
            PolSiteMap.HOME_INTERNET_TARIFFS_ELTEL,
            PolSiteMap.HOME_INTERNET_TARIFFS_CITYTELECOM,
            PolSiteMap.HOME_INTERNET_TARIFFS_STLAN,
            PolSiteMap.HOME_INTERNET_TARIFFS_NEWLINK,
            PolSiteMap.HOME_INTERNET_TARIFFS_YOUR_INTERNET,
            PolSiteMap.HOME_INTERNET_TARIFFS_MULTINEXT,
            PolSiteMap.HOME_INTERNET_TARIFFS_PAKT,
            PolSiteMap.HOME_INTERNET_TARIFFS_ANTHILL,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_LINER,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_KTV,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_SPB,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_POLUSTR,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_UNTOLOVO,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_PETRO,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_PAKT,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_ILAN,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_AVTOVO,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_ALFA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_GTK,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_TERABITA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_LAXTA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_LETUS,
            PolSiteMap.HOME_INTERNET_TARIFFS_WELL,
            PolSiteMap.HOME_INTERNET_TARIFFS_M52,
            PolSiteMap.HOME_INTERNET_TARIFFS_NEWLAIN,
            PolSiteMap.HOME_INTERNET_TARIFFS_GARS,
            PolSiteMap.HOME_INTERNET_TARIFFS_UNIWEB,
            PolSiteMap.HOME_INTERNET_TARIFFS_POSITIVE,
            PolSiteMap.HOME_INTERNET_TARIFFS_PRIMORSKAYA,
            PolSiteMap.HOME_INTERNET_TARIFFS_CONNECT,
            PolSiteMap.HOME_INTERNET_TARIFFS_TASKOM,
            PolSiteMap.HOME_INTERNET_TARIFFS_ALTERO,
            PolSiteMap.HOME_INTERNET_TARIFFS_YOTA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_RADUGA,
            PolSiteMap.HOME_INTERNET_TARIFFS_A_TEL,
            PolSiteMap.HOME_INTERNET_TARIFFS_NET_BUY,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_V,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_DELTA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_VINKY,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_ILKA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_TSS,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_VILTEL,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_SEVEREN,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_LOGINET,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_RED,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_OPTIKA,
            PolSiteMap.HOME_INTERNET_TARIFFS_TV_WESTCALL,
            PolSiteMap.OPERATOR_SBER,
            PolSiteMap.OPERATOR_TINKOFF,
            PolSiteMap.INERNET_PROV,
            PolSiteMap.PROVATE_HOUSE_INTER,
            PolSiteMap.TOHOME,
            PolSiteMap.OFFICE,
            PolSiteMap.BUSINESS,
            PolSiteMap.INTERNET_PROVIDERS,
            PolSiteMap.MOBILE_OPERATORS,
            PolSiteMap.TARIFFS,
            PolSiteMap.REVIEW_PROV,
            PolSiteMap.REVIEW_ELTEL,
            PolSiteMap.REVIEW_WELL,
            PolSiteMap.REVIEW_WEBA,
            PolSiteMap.CHOOSE_NUMBER,
            PolSiteMap.TARIFFS_YOTA,
            PolSiteMap.TARIFFS_BEELINE,
            PolSiteMap.CHOOSE_NUMBER_SBER,
            PolSiteMap.CHOOSE_NUMBER_MTC,
            PolSiteMap.CHOOSE_NUMBER_TINKOFF,
            PolSiteMap.CONTACTS,
        ]
        for url in url_click:
            try:
                element = self.element_is_visible(url)
                element.click()
                self.driver.back()
                print(f"Проверка {url} на карте покрытия пройдена")
            except AssertionError:
                print(f"Возникла ошибка с {url}")

    @allure.step("Проверить является ли страница недоступной")
    def click_on_url_and_back_mol(self):
        url_click = [
            MolSiteMap.HOME_INTERNET,
            MolSiteMap.INTERNET_PROVIDER_MGTS,
            MolSiteMap.INTERNET_PROVIDER_AKADO,
            MolSiteMap.INTERNET_RINET,
            MolSiteMap.INTERNET_PROVIDER_MTC,
            MolSiteMap.INTERNET_HOME_QVERTY,
            MolSiteMap.INTERNET_PROVIDER_2KOM,
            MolSiteMap.INTERNET_PROVIDER_LIFE,
            MolSiteMap.INTERNET_PROVIDER_AVAKS,
            MolSiteMap.INTERNET_PROVIDER_INTERLAIN,
            MolSiteMap.INTERNET_PROVIDER_NETBUNET,
            MolSiteMap.INTERNET_PROVIDER_VOKSNET,
            MolSiteMap.INTERNET_PROVIDER_LANTEK,
            MolSiteMap.HOME_INTERNET_TELEKOM,
            MolSiteMap.HOME_INTERNET_STARLINK,
            MolSiteMap.HOME_INTERNET_AKADEMNET,
            MolSiteMap.HOME_INTERNET_MOSNET,
            MolSiteMap.HOME_INTERNET_KURKINO,
            MolSiteMap.HOME_INTERNET_PROVRU,
            MolSiteMap.HOME_INTERNET_KOPTEVO,
            MolSiteMap.HOME_INTERNET_ELAINE,
            MolSiteMap.HOME_PROVIDER_BEELINE,
            MolSiteMap.HOME_INTERNET_ONLIME,
            MolSiteMap.HOME_INTERNET_MOSINTER,
            MolSiteMap.HOME_INTERNET_MASTERLINK,
            MolSiteMap.HOME_INTERNET_IAYZA,
            MolSiteMap.HOME_INTERNET_TELCOMNET,
            MolSiteMap.HOME_INTERNET_MEGANET,
            MolSiteMap.HOME_INTERNET_INFOSETI,
            MolSiteMap.HOME_INTERNET_RESORS,
            MolSiteMap.HOME_INTERNET_ALFASAT,
            MolSiteMap.HOME_INTERNET_VOLINA,
            MolSiteMap.HOME_INTERNET_RADUGA,
            MolSiteMap.HOME_INTERNET_KATRINET,
            MolSiteMap.HOME_INTERNET_MASTERTEL,
            MolSiteMap.HOME_INTERNET_MAVERIK,
            MolSiteMap.HOME_INTERNET_AMY,
            MolSiteMap.HOME_INTERNET_CITYTELEKOM,
            MolSiteMap.HOME_INTERNET_BITVEY,
            MolSiteMap.HOME_INTERNET_GARS,
            MolSiteMap.HOME_INTERNET_CONNECT,
            MolSiteMap.HOME_INTERNET_CONCOVO,
            MolSiteMap.HOME_INTERNET_ACBT,
            MolSiteMap.HOME_INTERNET_BITVEY,
            MolSiteMap.HOME_INTERNET_INFOTEL,
            MolSiteMap.HOME_INTERNET_IP,
            MolSiteMap.HOME_INTERNET_ULCOMNET,
            MolSiteMap.HOME_INTERNET_TERALINE,
            MolSiteMap.HOME_INTERNET_NORTNET,
            MolSiteMap.HOME_INTERNET_CLICK,
            MolSiteMap.HOME_INTERNET_PROF,
            MolSiteMap.HOME_INTERNET_ADYNET,
            MolSiteMap.HOME_INTERNET_ANDERS,
            MolSiteMap.HOME_INTERNET_ACONET,
            MolSiteMap.HOME_INTERNET_RIALCOM,
            MolSiteMap.HOME_INTERNET_MULTILINE,
            MolSiteMap.HOME_INTERNET_METRONET,
            MolSiteMap.HOME_INTERNET_ORANGE,
            MolSiteMap.HOME_INTERNET_TTK,
            MolSiteMap.HOME_INTERNET_AFFOTEL,
            MolSiteMap.HOME_INTERNET_POLISMA,
            MolSiteMap.HOME_INTERNET_TELECOM,
            MolSiteMap.HOME_INTERNET_TELEDISCONT,
            MolSiteMap.HOME_INTERNET_GLOBAL,
            MolSiteMap.HOME_INTERNET_NTK,
            MolSiteMap.HOME_INTERNET_VILAND,
            MolSiteMap.HOME_INTERNET_DOMOCOM,
            MolSiteMap.HOME_INTERNET_DINCOR,
            MolSiteMap.HOME_INTERNET_FLYTELECOM,
            MolSiteMap.HOME_INTERNET_REOLCOM,
            MolSiteMap.HOME_INTERNET_POLICOMM,
            MolSiteMap.HOME_INTERNET_INTEL,
            MolSiteMap.HOME_INTERNET_ZELTELECOM,
            MolSiteMap.OPERATOR_MOBILE,
            MolSiteMap.INTERNET_FOR_GARDEN,
            MolSiteMap.INTERNET_PROVIDERS,
            MolSiteMap.INTERNET_UR,
            MolSiteMap.MOBILE_OPERATORY,
            MolSiteMap.REVIEW_AKADO,
            MolSiteMap.REVIEW_LIFE,
            MolSiteMap.REVIEW_NETBYNET,
            MolSiteMap.REVIEW_CPMS,
            MolSiteMap.REVIEW_VIP,
            MolSiteMap.REVIEW_DNLAB,
            MolSiteMap.REVIEW_GORCOM,
            MolSiteMap.REVIEW_UNIONLINE,
            MolSiteMap.REVIEW_UCA,
            MolSiteMap.REVIEW_AISTEL,
            MolSiteMap.REVIEW_BUSINESS,
            MolSiteMap.REVIEW_INTERANET,
            MolSiteMap.REVIEW_ALFASAT,
            MolSiteMap.REVIEW_SKYLINK,
            MolSiteMap.REVIEW_LANSAT,
            MolSiteMap.REVIEW_SIMONOVO,
            MolSiteMap.REVIEW_CCS,
            MolSiteMap.REVIEW_CIFRA,
            MolSiteMap.REVIEW_MORTON,
            MolSiteMap.REVIEW_EASTNET,
            MolSiteMap.REVIEW_ECONOTEL,
            MolSiteMap.REVIEW_PROLINK,
            MolSiteMap.REVIEW_TELERU,
            MolSiteMap.REVIEW_SPARK,
            MolSiteMap.REVIEW_MEGALAN,
            MolSiteMap.SALES,
            MolSiteMap.PHONE_NETWORK,
            MolSiteMap.CHOOSE_NUM,
            MolSiteMap.MOBILE_MEGAFONE,
            MolSiteMap.MOBILE_MTC,
            MolSiteMap.HOME_INTERNET_TV,
            MolSiteMap.TARIFFS_CINEMA,
            MolSiteMap.TARIFFS_AKADO,
            MolSiteMap.TARIFFS_TV_MOBILE,
            MolSiteMap.TARIFFS_BEELINE,
            MolSiteMap.TARIFFS_MEGAFONE,
            MolSiteMap.TARIFFS_MANLINK,
            MolSiteMap.TARIFFS_NETBY,
            MolSiteMap.TARIFFS_WIFIRE,
            MolSiteMap.TARIFFS_LEGCHELIFE
        ]
        for url in url_click:
            try:
                element = self.element_is_visible(url)
                element.click()
                self.driver.back()
                print(f"Проверка {url} на карте покрытия пройдена")
            except AssertionError:
                print(f"Возникла ошибка с {url}")
